
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - common.scope.cluster.example.cn
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - common.scope.cluster.example.cn
  resources:
  - clusters/finalizers
  verbs:
  - update
- apiGroups:
  - common.scope.cluster.example.cn
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - study.example.cn
  resources:
  - worlds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - study.example.cn
  resources:
  - worlds/finalizers
  verbs:
  - update
- apiGroups:
  - study.example.cn
  resources:
  - worlds/status
  verbs:
  - get
  - patch
  - update
