# permissions for end users to view worlds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: world-viewer-role
rules:
- apiGroups:
  - study.example.cn
  resources:
  - worlds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - study.example.cn
  resources:
  - worlds/status
  verbs:
  - get
